#  specify the projectile option twice
# 
#  Projectile Options
#  proton = p
#  deuteron = d
#  Beryllium = Be
#  Copper = Cu
#  Oxygen = O_3pF
#  Argon = Ar_3pF
#  gold = Au
#  Uranium = Umus
#
#  Projectile
projectile = ION1
#  Target 
projectile = ION2
number-events = 100

output = OUTPUT_DIR

#  reduced thickness (p)
#  quadratic (default) = 0
#  linear (IP-GLASMA) = 42
#  Gluon Spectrum = 626
reduced-thickness = P_

#  fluctuation parameter
#  default = 1.6
#  corrected p42 = 50
fluctuation = K_
cross-section = CROSS_SECTION
nucleon-width = 0.32
nucleon-min-dist = 0.4

grid-max = 12
grid-step = 0.09
