trento_input_dir /projects/jnorhos/pcarzon/ICCING/testInput/
output_dir /projects/jnorhos/pcarzon/ICCING/testOutput/
input_type 1
output_type 1
seed_ 500

first_event 0
last_event 1
grid_max 12
grid_step 0.06

lambda_ 1
e_thresh 0.25
rad_ 0.5
qrad_ 0.5
tau_0 0.6
t_a 1
t_b 1
