input_folder /projects/jnorhos/pcarzon/ICCING/testInput/
output_folder /projects/jnorhos/pcarzon/ICCING/testOutput/
input_type 1
output_type 1

first_event 0
num_events 10
grid_max 12
grid_step 0.06

t_a 1
t_b 0
